---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-counters-cloudprog-polito-it-v1alpha1-podcounter
  failurePolicy: Fail
  name: mpodcounter.kb.io
  rules:
  - apiGroups:
    - counters.cloudprog.polito.it
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - podcounters
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-counters-cloudprog-polito-it-v1alpha1-podcounter
  failurePolicy: Fail
  name: vpodcounter-v1alpha1.kb.io
  rules:
  - apiGroups:
    - counters.cloudprog.polito.it
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - podcounters
  sideEffects: None
