---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods/status
  verbs:
  - get
- apiGroups:
  - counters.cloudprog.polito.it
  resources:
  - podcounters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - counters.cloudprog.polito.it
  resources:
  - podcounters/finalizers
  verbs:
  - update
- apiGroups:
  - counters.cloudprog.polito.it
  resources:
  - podcounters/status
  verbs:
  - get
  - patch
  - update
