name: Go Tests

on:
  pull_request:

jobs:
    test:
      runs-on: ubuntu-latest

      steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.23.2'

      - name: Run tests
        run: |
          cd ./git/timeapi
          go test -v -failfast -shuffle on ./...  -args -ginkgo.v
